### ISSUE TITLE
visibility and fPIC flags

### ISSUE THREAD

**Issue by baconpaul** [surge-synthesizer/surge-filesystem#3]
with SC3 to link I had to pass -fvisibility=none and -fPIC down to filesystem from the parent. The way I did it in the sc3 cmake file is obviously wrong. What is right?

**Comment by mvf** [comment]
I recently concluded that SC3 would be better off not using this code this at all, see #7.

To answer the question, basically what Surge does:
- Let CMake handle PIC via `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` before the top-level `project` call.
- Declare exported symbols `__attribute__((visibility("default")))` like in this [Surge commit](https://github.com/surge-synthesizer/surge/commit/c91cd9c5daeb871499ecffced7cda8764f2cafe4) (but probably via a macro for compatibility with MSVC). Visibility shouldn't affect `filesystem` though, since the only way it could have been linked shared (necessitating exported symbols) would be if the `BUILD_SHARED_LIBS` CMake variable was set.
